Test 2: main failed as expected
